### ISSUE TITLE
Create K8S configuration file

### ISSUE THREAD

**Issue by andyduong1920** [nimblehq/nimble-growth-39-k8s-aws-eks#10]
To deploy the CodeWar application.

Docker image: **301618631622.dkr.ecr.ap-southeast-1.amazonaws.com/nimble-growth-39-aws-eks:nimble-growth-39**

![image](https://user-images.githubusercontent.com/11751745/178449419-d5218442-078c-4431-a477-458a737a9aeb.png)

Example YAML configuration

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: myapp-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: myapp:release
          ports:
            - containerPort: 8000
          args: ["foreground"]
          env:
            - name: HOST
              value: "example.com"
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: secret_key_base
            - name: DB_USERNAME
              value: "postgres"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: db_password
            - name: DB_NAME
              value: "myapp_dev"
            - name: DB_HOSTNAME
              value: "10.0.2.2"
```
